GO_BRIDGE = """namespace {

// Results are allocated by the Go side with C.CString, so the caller frees them.
// A null result means the Go side recovered a panic and left the message in err.
std::string call_go(char* (*fn)(char*, char**), std::string_view input) {
    std::string owned{input};
    char* err = nullptr;
    char* result = fn(owned.data(), &err);
    if (!result) {
        std::string message{err ? err : "unknown panic"};
        std::free(err);
        throw std::runtime_error("go solution panicked: " + message);
    }
    std::string out{result};
    std::free(result);
    return out;
}

} // namespace
"""

GO_SOLUTION = """class Day{day}Go : public aoc::Solution {{
  public:
    std::string p1(std::string_view input) override {{ return call_go(Day{day}P1, input); }}
    std::string p2(std::string_view input) override {{ return call_go(Day{day}P2, input); }}
}};
"""

def _generate_dispatcher_impl(ctx):
    includes = []
    classes = []
    cases = []

    for f in sorted(ctx.files.srcs, key = lambda f: f.basename):
        name = f.basename
        number_str = name.removeprefix("day").removesuffix(".hpp")

        if not number_str.isdigit():
            fail("File {} does not match format dayXX.hpp".format(name))

        day_num = int(number_str)
        day_str = "0" + str(day_num) if day_num < 10 else str(day_num)

        includes.append('#include "solutions/{}"'.format(name))
        cases.append((day_num, "        case {}: return std::make_unique<Day{}>();".format(day_num, day_str)))

    if ctx.attr.go_days:
        includes.append('#include "{}"'.format(ctx.attr.go_header))
        classes.append(GO_BRIDGE)

        for day_str in sorted(ctx.attr.go_days):
            classes.append(GO_SOLUTION.format(day = day_str))
            cases.append((int(day_str), "        case {}: return std::make_unique<Day{}Go>();".format(int(day_str), day_str)))

    content = """// GENERATED BY BAZEL - DO NOT EDIT
#include "aoc.hpp"
#include <cstdlib>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
{includes}

{classes}
std::unique_ptr<aoc::Solution> get_solution(int day) {{
    switch (day) {{
{cases}
        default: return nullptr;
    }}
}}
""".format(
        includes = "\n".join(includes),
        classes = "\n".join(classes),
        cases = "\n".join([text for _, text in sorted(cases)]),
    )

    outfile = ctx.actions.declare_file(ctx.attr.out_name)
    ctx.actions.write(output = outfile, content = content)

    return [DefaultInfo(files = depset([outfile]))]

generate_dispatcher = rule(
    implementation = _generate_dispatcher_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
        "go_days": attr.string_list(),
        "go_header": attr.string(),
        "out_name": attr.string(default = "dispatcher.cpp"),
    },
)
