def _generate_dispatcher_impl(ctx):
    includes = []
    cases = []

    sorted_files = sorted(ctx.files.srcs, key = lambda f: f.basename)

    for f in sorted_files:
        name = f.basename

        number_str = name.removeprefix("day").removesuffix(".hpp")

        if not number_str.isdigit():
            fail("File {} does not match format dayXX.hpp".format(name))

        day_num = int(number_str)
        day_str = "0" + str(day_num) if day_num < 10 else str(day_num)
        class_name = "Day{}".format(day_str)

        includes.append('#include "solutions/{}"'.format(name))
        cases.append('        case {}: return std::make_unique<{}>();'.format(day_num, class_name))

    content = """// GENERATED BY BAZEL - DO NOT EDIT
#include "aoc.hpp"
#include <memory>
{includes}

std::unique_ptr<aoc::Solution> get_solution(int day) {{
    switch (day) {{
{cases}
        default: return nullptr;
    }}
}}
""".format(
        includes = "\n".join(includes),
        cases = "\n".join(cases)
    )

    # 3. Write the file
    # This happens instantly during the build graph creation
    outfile = ctx.actions.declare_file(ctx.attr.out_name)
    ctx.actions.write(output = outfile, content = content)

    return [DefaultInfo(files = depset([outfile]))]

# Define the rule interface
generate_dispatcher = rule(
    implementation = _generate_dispatcher_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
        "out_name": attr.string(default = "dispatcher.cpp"),
    },
)
