"""Discovers Go solutions under go/dayXX/ and wires them into the C++ runner.

Every Go day is compiled into a single c-archive: each archive embeds its own
copy of the Go runtime, so linking more than one into aoc2025 would collide on
duplicate symbols.
"""

load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

IMPORTPATH_PREFIX = "github.com/khayyamsaleem/advent-of-code/2025/go"

# External deps needed by individual days, keyed by day number.
EXTRA_DEPS = {
    "02": ["@org_golang_x_sync//errgroup"],
}

def _bridge_src_impl(ctx):
    imports = []
    exports = []

    for day in ctx.attr.days:
        pkg = "day" + day
        imports.append('\t{pkg} "{prefix}/{pkg}"'.format(pkg = pkg, prefix = IMPORTPATH_PREFIX))
        for part in ("1", "2"):
            exports.append("""//export Day{day}P{part}
// Recovers panics: one unwinding out of an //export'd function aborts the whole
// runner and cannot be caught from C++. On panic the result is nil and *errOut
// holds the message, which the C++ bridge turns into an exception.
func Day{day}P{part}(input *C.char, errOut **C.char) (result *C.char) {{
\tdefer func() {{
\t\tif r := recover(); r != nil {{
\t\t\tresult, *errOut = nil, C.CString(fmt.Sprint(r))
\t\t}}
\t}}()
\treturn C.CString({pkg}.P{part}(C.GoString(input)))
}}""".format(day = day, part = part, pkg = pkg))

    import_block = "import (\n\t\"fmt\"\n\n{}\n)\n\n".format("\n".join(imports)) if imports else ""

    content = """// GENERATED BY BAZEL - DO NOT EDIT
package main

// #include <stdlib.h>
import "C"

{import_block}{exports}

func main() {{}}
""".format(import_block = import_block, exports = "\n\n".join(exports))

    outfile = ctx.actions.declare_file(ctx.attr.out_name)
    ctx.actions.write(output = outfile, content = content)
    return [DefaultInfo(files = depset([outfile]))]

_bridge_src = rule(
    implementation = _bridge_src_impl,
    attrs = {
        "days": attr.string_list(),
        "out_name": attr.string(),
    },
)

def discover_go_days(srcs):
    """Maps day number -> {"srcs": [...], "tests": [...]} from go/dayXX/*.go paths."""
    days = {}

    for f in srcs:
        parts = f.split("/")
        if len(parts) != 3:
            fail("Go solution {} must live at go/dayXX/<file>.go".format(f))

        number_str = parts[1].removeprefix("day")
        if not number_str.isdigit():
            fail("Directory {} does not match format go/dayXX/".format(parts[1]))

        day = number_str
        if day not in days:
            days[day] = {"srcs": [], "tests": []}
        days[day]["tests" if f.endswith("_test.go") else "srcs"].append(f)

    return days

def go_solutions(name, days):
    """Declares a go_library + go_test per day, and one shared c-archive."""
    libs = []

    for day in sorted(days):
        lib = "day{}_go".format(day)
        libs.append(":" + lib)

        go_library(
            name = lib,
            srcs = days[day]["srcs"],
            importpath = "{}/day{}".format(IMPORTPATH_PREFIX, day),
            deps = EXTRA_DEPS.get(day, []),
        )

        if days[day]["tests"]:
            go_test(
                name = "day{}_go_test".format(day),
                srcs = days[day]["tests"],
                embed = [":" + lib],
                size = "small",
            )

    _bridge_src(
        name = name + "_src",
        days = sorted(days),
        out_name = name + ".go",
    )

    # Emits <name>.a plus a generated <name>.h declaring the //export'd symbols.
    go_binary(
        name = name,
        srcs = [":" + name + "_src"],
        cgo = True,
        linkmode = "c-archive",
        deps = libs,
    )
