[package]
name = "aoc-2024-day-03"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
recap = { git = "https://github.com/khayyamsaleem/recap", branch="master"}
serde = "1.0.215"
