version: '3'
services:
    intcode-server:
        image: registry.gitlab.com/advent-of-code:intcode
        networks: 
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host: intcode.khayyam.me"

networks:
  web:
    external:
      name: server_webgateway
