version: '3'
services:
    intcode-server:
        build: .
        networks: 
            - webgateway
        depends_on: 
            - reverse-proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.intcode-server.rule=Host(`intcode.docker.localhost`)"
        
    reverse-proxy:
        image: "traefik:2.0"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        networks: 
            - webgateway
        ports:
            - "80:80"
            - "8080:8080"
        labels:
            traefik.enable: "true"
            traefik.backend: "traefik"
            traefik.port: "8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  webgateway:
    driver: bridge